language: node_js
node_js:
  - 16
services:
  - mongodb
cache:
  directories:
    - node_modules
before_install:
  - yarn install
  - export NODE_ENV=production
script:
  - yarn test-babel-dev
  - yarn lint
